name: continuous-integration
on: [pull_request]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: yarn install
      - run: yarn lint --max-warnings 0
      - run: yarn test
